INSERT INTO CLIENT VALUES (1, 'TOTO', 200.0);
INSERT INTO CLIENT VALUES (2, 'TITI', 20.0);
INSERT INTO CLIENT VALUES (3, 'TITI', 20.0);
INSERT INTO CLIENT VALUES (5, 'TATA', 120.0);
INSERT INTO CLIENT VALUES (15, 'BOF', 150.0);
INSERT INTO CLIENT VALUES (16, 'BIF', 150.0);

INSERT INTO CLIENT VALUES (5, 'TUTU', 200.0);

INSERT INTO CLIENT VALUES (20, 'RIRI', NULL);
INSERT INTO CLIENT (ID, NOM) VALUES (21, 'FIFI');
INSERT INTO CLIENT (ID, SOLDE) VALUES (22, 150);
INSERT INTO CLIENT (NOM) VALUES ('LOULOU');

INSERT INTO PRODUCTEUR VALUES ( 1, 'BRICOLOT');
INSERT INTO PRODUCTEUR VALUES ( 2, 'FRUIT AND FIBRE');

INSERT INTO PRODUIT (ID, NOM, PRIX_UNITAIRE, PRODUCTEUR)
VALUES (1, 'CLOU', 11.0, 1);
INSERT INTO PRODUIT (ID, NOM, PRIX_UNITAIRE, PRODUCTEUR)
VALUES ( 2,'ROBINET', 30.0, 1);
INSERT INTO PRODUIT (ID, NOM, PRIX_UNITAIRE, PRODUCTEUR)
VALUES ( 3, 'KIWI', 0.3, 2);

INSERT INTO COMMANDE VALUES (2, 2, 3);
INSERT INTO COMMANDE VALUES (2, 3, 20);
INSERT INTO COMMANDE VALUES (5, 1, 100);
INSERT INTO COMMANDE VALUES (5, 3, 10);
