SELECT * FROM CLIENT;
UPDATE CLIENT SET SOLDE = SOLDE + 10.0;
SELECT * FROM CLIENT;

UPDATE CLIENT
SET SOLDE = SOLDE - 30.0, NOM = 'TOTO'
WHERE ID = 2;
SELECT * FROM CLIENT;

UPDATE CLIENT
SET SOLDE = SOLDE + 30.0
WHERE SOLDE BETWEEN 100.0 AND 180.0;
SELECT * FROM CLIENT;